package net.chiovari.javarecipes.jpa2cert.entities.id;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Created by cristianchiovari on 04/01/14.
 * Sql
 * CREATE TABLE ENTITYWITHIDIDENTITY
 * (ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 * SOMEFIELD VARCHAR(255), PRIMARY KEY (ID))
 */
@Entity
public class EntityWithIDIdentity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String someField;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSomeField() {
        return someField;
    }

    public void setSomeField(String someField) {
        this.someField = someField;
    }
}
